= CS-tap-in Application API Document
:doctype: book
:icons: font
:source-highlighter: highlightjs
:toc: left
:toclevels: 2
:sectlinks:

[[auth]]
== 인증

=== 일반 로그인

operation::auth-login[snippets='http-request']
|===
| key | type | description | required
| password | String +
pattern: 영문, 숫자, 특수기호 조합 8~15자 이내  | 비밀번호 | O
| username | String +
pattern: 영문/숫자 2~20자 이내 | 아이디 | O
|===

operation::auth-login[snippets='http-response']
|===
| key | type | description | required
| accessToken | String | access token | O
| refreshToken | String | refresh token | O
|===

=== 관리자 회원가입

operation::join-admin[snippets='http-request']
|===
| key | type | description | required
| password | String +
pattern: 영문, 숫자, 특수기호 조합 8~15자 이내  | 비밀번호 | O
| username | String +
pattern: 영문/숫자 2~20자 이내 | 아이디 | O
|nickname | String +
pattern: 4자 이상 | 별명 | O
|secretKey | String | 관리자 비밀 key | O
|===
NOTE: secretKey는 관리자에게 문의하세요.

operation::join-admin[snippets='http-response']
|===
| key | type | description | required
|===

=== [관리자] 퀴즈 생성

operation::admin-create-quiz[snippets='http-request']
|===
| key | type | description | required
| problem | String | 문제 +
정답이 들어가는 부분은 "\+++"로 대체한다.| O
| answer | String +
pattern: 영문/숫자 2~20자 이내 | 아이디 | O
| title | String +
pattern: 4자 이상 | 별명 | O
| categoryId | String | 관리자 비밀 key | O
|===

operation::admin-create-quiz[snippets='http-response']
|===
| key | type | description | required
|===